export const CREATE_DOCUMENT_ERROR = 'CREATE_DOCUMENT_ERROR';
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT_ERROR = 'DELETE_DOCUMENT_ERROR';
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
export const UPDATE_DOCUMENT_ERROR = 'UPDATE_DOCUMENT_ERROR';
export const UPDATE_DOCUMENT_SUCCESS = 'UPDATE_DOCUMENT_SUCCESS';
export const UPDATE_COUNT_SUCCESS = 'UPDATE_COUNT_SUCCESS';
export const UPDATE_COUNTY_SUCCESS = 'UPDATE_COUNTY_SUCCESS';
export const CREATE_COUNTY_SUCCESS = 'CREATE_COUNTY_SUCCESS';

